services:
  app:
    build:
      context: ./ez_decks
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '${NODEAPP_PORT}:${NODEAPP_PORT}'
      - '5555:5555'
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV:-development}  # Dynamically set based on .env or default to development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    volumes:
      - ./ez_decks:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 0.5G
          cpus: '0.5'

  db:
    image: postgres:16-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
