services:
  app:
    build:
      context: ./ez_decks
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '${NODEAPP_PORT}:${NODEAPP_PORT}'
      - '5555:5555' # For prisma studio
    depends_on:
      - db
      - queue
    env_file:
      - ./ez_decks/.env
      - ./ez_decks/.env.${NODE_ENV}.local
    volumes:
      - ./ez_decks:/usr/src/app
      - ./ez_decks/logs:/usr/src/app/logs
      - type: tmpfs
        target: ${NODE_TEMP_PATH:-/tmp}
   #  deploy:
   #    resources:
   #      limits:
   #        memory: 1G
   #        cpus: '0.5'

  db:
    image: postgres:16-bookworm
    container_name: postgres_db
    env_file:
      - ./ez_decks/.env
      - ./ez_decks/.env.${NODE_ENV}.local
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

  queue:
    image: redis:7.4.1-bookworm
    container_name: redis_queue
    env_file:
      - ./ez_decks/.env
      - ./ez_decks/.env.${NODE_ENV}.local
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - type: tmpfs
        target: /data
    command: redis-server --port ${REDIS_PORT} --loglevel debug
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'

volumes:
  postgres_data:
