services:
  app:
    build:
      context: ./ez_decks
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - '${NODEAPP_PORT}:${NODEAPP_PORT}'
      - '5555:5555'
    depends_on:
      - db
    env_file:
      - ./ez_decks/.env
      - ./ez_decks/.env.${NODE_ENV}.local
    volumes:
      - ./ez_decks:/usr/src/app
   #  deploy:
   #    resources:
   #      limits:
   #        memory: 1G
   #        cpus: '0.5'

  db:
    image: postgres:16-bookworm
    container_name: postgres_db
    env_file:
      - ./ez_decks/.env
      - ./ez_decks/.env.${NODE_ENV}.local
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
